name: Publish Docker

on:
  pull_request:
    types: [closed]
    branches:
    - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BRANCH_FILTER: "master"
  DOCKER_NAMESPACE: "bitwyre"
  DOCKER_IMAGE_NAME: "base-images"

jobs:
  apidocs:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04]
    env:
      DOCKER_IMAGE_TAG: "apidocs"
    steps:
    - uses: actions/checkout@master
    - name: Pull previous image for cache
      run: docker pull $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - name: Build and Publish to Docker Hub
      uses: pangzineng/Github-Action-One-Click-Docker@master
      with:
        args: "-f apidocs.Dockerfile ."

  grpc:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        # os: [ubuntu-18.04]
        os: [self-hosted]
    env:
      DOCKER_IMAGE_TAG: "grpc-alpine"
    steps:
    - uses: actions/checkout@master
    - name: Pull previous image for cache
      run: docker pull $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - name: Build and Publish to Docker Hub
      uses: pangzineng/Github-Action-One-Click-Docker@master
      with:
        args: "-f grpc.Dockerfile ."

  python:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        # os: [ubuntu-18.04]
        os: [self-hosted]
    env:
      DOCKER_IMAGE_TAG: "python-alpine"
    needs: [grpc]
    steps:
    - uses: actions/checkout@master
    - name: Pull previous image for cache
      run: docker pull $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - name: Build and Publish to Docker Hub
      uses: pangzineng/Github-Action-One-Click-Docker@master
      with:
        args: "-f python.Dockerfile ."

  python-dev:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        # os: [ubuntu-18.04]
        os: [self-hosted]
    env:
      DOCKER_IMAGE_TAG: "python-dev-alpine"
    needs: [grpc, python]
    steps:
    - uses: actions/checkout@master
    - name: Pull previous image for cache
      run: docker pull $DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - name: Build and Publish to Docker Hub
      uses: pangzineng/Github-Action-One-Click-Docker@master
      with:
        args: "-f python-dev.Dockerfile ."
